version: "3.8"

services:
  proxy:
    image: dperson/torproxy
    container_name: torproxy
    restart: always
    ports:
      - 8118:8118
      - 9050:9050
    networks:
      - lognet

  scraper:
    container_name: scrape-machine
    restart: always
    build: ./project-scrape-machine
    volumes:
      - .:/usr/src/app
    depends_on:
      - proxy
      - mongo
      - api
    networks:
      - lognet

  api:
    container_name: api-container-node-mongo
    restart: always
    build: ./project-api-server
    ports:
      - 4000:4000
    depends_on:
      - mongo
    networks:
      - lognet

  client:
    container_name: client-container
    restart: always
    build: ./project-client
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - lognet

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./project-database/db:/data/db
    networks:
      - lognet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - lognet

networks:
  lognet:
    driver: bridge
