version: "3.8"

services:
  proxy:
    image: dperson/torproxy
    container_name: torproxy
    restart: unless-stopped
    ports:
      - 8118:8118
      - 9050:9050

  scraper:
    container_name: scrape-machine
    restart: unless-stopped
    build: ./project-scrape-machine
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - proxy
      - mongo
    links:
      - mongo
      - proxy

  api:
    container_name: api-container-node-mongo
    restart: unless-stopped
    build: ./project-api-server
    ports:
      - 4000:4000
    links:
      - mongo
    depends_on:
      - proxy
      - scraper
      - mongo

  client:
    container_name: client-container
    restart: unless-stopped
    build: ./project-client
    ports:
      - 3000:3000
    depends_on:
      - api

  mongo:
    container_name: mongo-container
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./project-database/dbTesting:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
